name: Run Flask App

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      # Run the Flask application
      - name: Run Flask App
        run: |
          python app.py &
